### ISSUE TITLE
Hide pager indicator

### ISSUE THREAD

**Issue by drdla49** [apl-devs/AppIntro#340]
Hi, please is there any way how to easy hide pager indicator?
setProgressButtonEnabled hide buttons but not pager indicator. 
I use setVisibility(GONE) to indicator_container. 
But is there any easy way to hide all on buttom?
Thank you.

**AppIntro Version**: 4.1.0

**Device/Android Version**: All devices, all version of Android

**Comment by ritdaw** [comment]
+1

**Comment by avluis** [comment]
The easy way to hide the indicator is by changing the visibility of `R.id.indicator_container`.
You can grab that like so:
```java
FrameLayout indicatorContainer = (FrameLayout) findViewById(R.id.indicator_container);
```
And then you can apply visibility on that.

**Comment by Andrew-Quebe** [comment]
@avluis your way works, but a dedicated method would be nice.

**Comment by paolorotolo** [comment]
@avluis @Andrew-Quebe are you guys OK to add a new method for this?

**Comment by paolorotolo** [comment]
Done, see PR #457
