### ISSUE TITLE
Make resources private

### ISSUE THREAD

**Issue by Jawnnypoo** [apl-devs/AppIntro#389]
You should make resources such as the drawables private, see more [here](https://developer.android.com/studio/projects/android-library.html)

If this is not an option, then you should prepend something like `appintro` or `ai_` to all the resources you use that are not meant to be public, such as

`ic_arrow_back_white` -> `appintro_ic_arrow_back_white`

**Comment by Jawnnypoo** [comment]
The reasoning is that a user may end up naming one of their resources `ic_arrow_back_white` and it would replace the library asset, and they would be unaware of this issue.

**Comment by avluis** [comment]
@Jawnnypoo  Can you create a PR with the string name changes -- keep them public.
Do note I am referring to the library only -- not the example app.

As for the prefix itself, `appintro_` should do.

**Comment by Andrew-Quebe** [comment]
@Jawnnypoo closing this for now...if you make a PR, I'll attach it to the 4.2.0 milestone.
