### ISSUE TITLE
Custom Fragment Layout overlapping with step indicator

### ISSUE THREAD

**Issue by rohitsuratekar** [apl-devs/AppIntro#393]
Using "compile 'com.github.paolorotolo:appintro:4.1.0' "
Devices with issue : Android Emulator (Nexus 4), Moto G3 (both with Android 7)

I am using custom fragment like following,

MainActivity.java

    public class MainActivity extends AppIntro {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addSlide(new MyFragment());
        //Other code
       }

MyFragment.java

     public class MyFragment extends Fragment {
       @Nullable
      @Override
        public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
          View rootView = inflater.inflate(R.layout.fragment, container, false);
          return rootView;
      }

fragment.xml

    <?xml version="1.0" encoding="utf-8"?>
     <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
     android:orientation="vertical" android:layout_width="match_parent"
     android:gravity="bottom"
     android:layout_height="match_parent">
    <Button
        android:text="Button"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/button" />
    </LinearLayout>

Manifest

     <activity
            android:name=".MainActivity"
            android:theme="@style/Theme.AppCompat.Light.DarkActionBar" />

Issue: 
**Whenever I am putting any view at the bottom of fragment layout, it is overlapping with step indicator.** (e.g. for example, I used gravity bottom for attached screenshot. )

Things I have tried:
Changing location/sequence of fragment, changing activity style, adding more views/removing views .

![screenshot_1483101509](https://cloud.githubusercontent.com/assets/8757115/21565195/fb2b1c50-ceba-11e6-9de4-d9d92e08267e.png)

**Comment by rohitsuratekar** [comment]
Corrected code indent

**Comment by avluis** [comment]
You need to follow the custom fragment example (custom slide) and include your own view in one of the containers shown in the sample xml layouts -- simply dropping a button into a layout will result in the above, AppIntro library or not.

**Comment by Andrew-Quebe** [comment]
What @avluis said.
