### ISSUE TITLE
Error:The number of method references in a .dex file cannot exceed 64K.

### ISSUE THREAD

**Issue by Excel1** [apl-devs/AppIntro#399]
I installed the lib: Copy the Build.Gradle text and paste it.

After this i created the Activities wtih appintro, but i tried to build my apk and then i got the Error like in the log.

AppIntro: 4.1.0 (also tested 4.0.0)

Every Device (I got the Error in Android Studio)

log:
Gradle building

```

Error:The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

```

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

GRADLE BUILD FAILED

**Comment by Andrew-Quebe** [comment]
How many methods and classes does your app have without our library? This is generally a result of too many classes in one app...you should consider following that link it told you to go to to fix it. 

If you don't have anything else in your app (provide proof of this please), then we'll consider a bug with the library. Though, you are the only person that's mentioned this, and considering that I've used the library several times in my projects without fail, I think it may be your code.

**Comment by Excel1** [comment]
Yes i tried, but i get following problems:

Error:UNEXPECTED TOP-LEVEL ERROR:
Error:java.lang.OutOfMemoryError: GC overhead limit exceeded
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException


And i know, that my App dont create these errors without multidex, which i need for the lib.

I disabled all my other libs, but i need only for these lib multidex, which wont work.

**Comment by Excel1** [comment]
It now works. 

For me was multidex required!

**Comment by Andrew-Quebe** [comment]
Glad you got it working.
