### ISSUE TITLE
Png alternative for vector images ?

### ISSUE THREAD

**Issue by shaheenkdr** [apl-devs/AppIntro#404]
I am in a situation where I need to compile my app with  compileSdkVersion and  buildToolsVersion at V22, as my image processing libraries are not fully supported for 23+ . Now the issue is this : all the images in the drawable folder of the library are in Vector form, since I cant use 23+ , I also can't use app:srcCompat to render them as well, android:src fails as well. So do you guys have a time machine that goes back, and that'd kindly give all the png formats of these vector images for this poor lad?

Thanks,

**Comment by avluis** [comment]
A note for you;
You can keep `targetSdkVersion` at 22 and update `compileSdkVersion` to 25 and `buildToolsVersion` to '25.0.2'.

On a different note, you can make use of AppCompat to handle Vector drawables for older SDK levels with `vectorDrawables.useSupportLibrary = true` (insert that into the defaultConfig block of your app level build.gradle).

If you can't figure out how to make use of the info above, you could navigate the commit history until you find where the images were swapped into vectors or, if you can't find them, extract the path data from each vector and reconstruct the image by making use of image editing software and a text editor (create a sample vector image in the software of your choice, save, and open said file with a text editor like notepad++ if on Windows -- TextWrangler if on OSX).

**Comment by shaheenkdr** [comment]
Hey, thanks for replying, even after retrieving png's from old version, I still do not get any buttons while the screen is rendered, I do get all the images and I am able to swipe the fragments as well, text is also rendering quite good, the problem is with imagebuttons. Here is my code:

```
public class OnBoard extends AppIntro2
{
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addSlide(AppIntroFragment.newInstance("Welcome!", "This is a demo of the AppIntro library, using the second layout.", R.drawable.messo, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Clean App Intros", "This library offers developers the ability to add clean app intros at the start of their apps.", R.drawable.messo, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Simple, yet Customizable", "The library offers a lot of customization, while keeping it simple for those that like simple.", R.drawable.messo, Color.parseColor("#1976D2")));
        addSlide(AppIntroFragment.newInstance("Explore", "Feel free to explore the rest of the library demo!", R.drawable.messo, Color.parseColor("#1976D2")));
        // Hide Skip/Done button.
        showSkipButton(false);
        setProgressButtonEnabled(false);

        // Turn vibration on and set intensity.
        // NOTE: you will probably need to ask VIBRATE permission in Manifest.
        setVibrate(true);
        setVibrateIntensity(30);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        // Do something when users tap on Done button.
    }

    @Override
    public void onSlideChanged(@Nullable Fragment oldFragment, @Nullable Fragment newFragment) {
        super.onSlideChanged(oldFragment, newFragment);
        // Do something when the slide changes.
    }

}
```

Here is my app level gradle file :

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.0"

    defaultConfig {
        applicationId "com.example.xyz"
        vectorDrawables.useSupportLibrary = true
        minSdkVersion 17
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile project(':library')

}
```

Has there been any issue of this kind before? Kindly help :)

**Comment by avluis** [comment]
I would start by removing the `vectorDrawables.useSupportLibrary = true` if you aren't going to update your build tools (this is also a v23 support lib dependent, not recommended on lower -- not sure even if it does anything on lower level).

When you say you don't get any buttons -- are they physically there or hidden (make use of the `show layout bounds` option in dev options)?

There is not much I can help you with at this point unless you attach logcat to see if it is throwing any errors, etc. Some pictures of the issue would do good as well.

**Comment by avluis** [comment]
@shaheenkdr I noticed that you opened another issue -- has this issue been resolved?

**Comment by shaheenkdr** [comment]
Yes this has been resolved , thanks for the support. Now need help with the other :)

**Comment by avluis** [comment]
Is this your first time making use of GitHub? Once an issue is resolved, as the creator, it is best to close it.
We can close it as well, but we rather confirm that is has been resolved first.
Please keep this in mind when creating further issues in any repo.
