### ISSUE TITLE
How to add background color transition?

### ISSUE THREAD

**Issue by shaheenkdr** [apl-devs/AppIntro#405]
I am trying to enable the background color transition, and this is my code:

```
public class AppIntro extends AppIntro2 implements ISlideBackgroundColorHolder
{

    @Override
    public int getDefaultBackgroundColor() {
        // Return the default background color of the slide.
        return Color.parseColor("#000000");
    }

    @Override
    public void setBackgroundColor(@ColorInt int backgroundColor) {
        // Set the background color of the view within your slide to which the transition should be applied.
        if (layoutContainer != null) {
            layoutContainer.setBackgroundColor(backgroundColor);
        }
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        showSkipButton(false);
        showStatusBar(false);
        addSlide(AppIntroFragment.newInstance("Hello", "world", R.drawable.bunny, Color.parseColor("#FFB300")));
        
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        finish();
    }
}

```

Now the issue is pretty small. ie I cannot resolve ```layoutContainer``` in Android Studio. What should I replace it with if I am using ```AppIntro2``` ? I searched the entire repo for ```layoutContainer```, however it is only seen in the readme  file it seems.

Kindly help,
:)

**Comment by avluis** [comment]
I would compare your code against the example code in the repo.
Unfortunately, some of that example code has not made it over just yet to the new example app, but this is GitHub so this is not really an issue -- check out [this directory](https://github.com/apl-devs/AppIntro/tree/726261aa421a8a27b005b8f078b3f8a0aba8fe79/example/src/main/java/com/github/paolorotolo/appintroexample/animations) with the previous examples (related to animations).

**Comment by NovaViper** [comment]
I found a way to enable the transition colors, you need to put the `setColorTransitionsEnabled `to `true`

**Comment by shaheenkdr** [comment]
@NovaViper  Thanks for helping! @avluis  Now you may close this!

**Comment by NovaViper** [comment]
Np, I was figuring out the same thing and I happened to look into the source code and saw that you had to enable that setting to achieve the color transitions, since its false by default

**Comment by avluis** [comment]
@shaheenkdr Please close your own issues -- no need to wait on us...

**Comment by HammadN** [comment]
@NovaViper where is this `setColorTransitionsEnabled`?
