### ISSUE TITLE
newInstance() in Appintro Fragment cannot be applied to:

### ISSUE THREAD

**Issue by Excel1** [apl-devs/AppIntro#410]
addSlide(AppIntroFragment.newInstance(R.string.appinfo_updateinfo_Error, R.string.appinfo_updateinfo_Error_txt, R.drawable.ic_updateinfo_error , Color.parseColor("#e65100")));
        addSlide(AppIntroFragment.newInstance(R.string.appinfo_updateinfo_futureversion, R.string.appinfo_updateinfo_futureversion_txt, R.drawable.ic_updateinfo_thumbsup , Color.parseColor("#212121")));

version of AppIntro: 4.1.0

Failed by developing in Android Studio

newInstance() in AppIntroFragment cannot be applied to:
Expected Parameters:
Actual Arguments:
 
title:
java.lang.CharSequence
R...string.appinfo_updateinfo_futureversion  (int) [ERROR]
description:
java.lang.CharSequence
R...appinfo_updateinfo_futureversion_txt  (int) [ERROR]
imageDrawable:
int
R.drawable.ic_updateinfo_thumbsup  [WORK]
bgColor:
int
Color.parseColor("#212121")  [WORK]

**Comment by Excel1** [comment]
Only works by sorrunding with ""+ like: addSlide(AppIntroFragment.newInstance(""+R.string.appinfo_updateinfo_futureversion, ""+R.string.appinfo_updateinfo_futureversion_txt, R.drawable.ic_updateinfo_thumbsup , Color.parseColor("#212121")));

**Comment by Excel1** [comment]
Could this Issue be removed please? :)

**Comment by cortinico** [comment]
@Excel1 this issue is really old, can I ask you to open a new one if you have a newer bug to report?
