### ISSUE TITLE
how can I set text color in app intro ?? 

### ISSUE THREAD

**Issue by hieuxinhe94** [apl-devs/AppIntro#412]
**AppIntro Version**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=android+set+text+color&*
