### ISSUE TITLE
Asking for permission cause the intro not slide

### ISSUE THREAD

**Issue by mohamed-elsabagh** [apl-devs/AppIntro#414]
I don't know why but whenever I add ask permissions in the activity, and I launch the application I can't go to the next slide by swiping the screen, but I have to press the arrow key and this is the only way I can get to the next slide

**Comment by avluis** [comment]
@Andrew-Quebe This needs to be added to the README in bold in the permissions section.
@mohamed-elsabagh Swiping is disabled when requesting permissions.

**Note:** There was a comment on how to address this behavior on a prior discussion but I'm not sure if it went anywhere after that.
