### ISSUE TITLE
Ask Permisssion for last slide not working

### ISSUE THREAD

**Issue by razeghi71** [apl-devs/AppIntro#416]

**Comment by avluis** [comment]
**AppIntro Version**:


**Device/Android Version**:


**Issue details / Repro steps / Use case background**: 


**Your Code**: 


**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Limitin** [comment]
I've seen this same problem.

The problem with this is the permission request is called inside of the NextButtonOnClickListener. On the last slide, there is no next button, but rather, a done button.

**Comment by avluis** [comment]
Issue here is that there should be no permission requests on the last slide, meaning; you can either add an additional slide after the slide that requests permissions or you can move that permission request before the last slide.
If you absolutely require the last slide to support permissions, then some modification to the codebase will be needed -- if you have time for a PR, please submit one for review 😻
