### ISSUE TITLE
Problem with Skip button [Noob Developer]

### ISSUE THREAD

**Issue by IcyTower1337** [apl-devs/AppIntro#421]
Hello, 

I am new to android coding and coding in general, I'm trying to make a simple app with AppIntro to test my skills and see if i can get better at coding android apps.

I've been able to create slides and make the app start with that activity, but I am now trying to add functionality to the skip button, i used this piece of code found both in the video and in the github for this project 

`@Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish();
    }`

when I try to compile, it gives me these errors:

> Error:(28, 31) error: cannot find symbol class Fragment

> Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Can someone help me? I'm new to this and i've tried to google the issue but i can't get it to work.

Screenshot of what the issue seems to be:

[http://puu.sh/uyhi6/95f4f6f7c2.png](url)

Thank you for your time,
IcyTower1337

**Comment by avluis** [comment]
Are you importing Fragment from the Support library?
Go ahead and post the whole file here, this lets us get a much better picture of what is going on.

**Comment by IcyTower1337** [comment]
I'm not sure what you mean, again I'm a noob when it comes to android coding. 

You want me to send the whole folder of the project? 

I tried pasting it but it's bigger than 10 MB so im uploading it to dropbox.

https://www.dropbox.com/s/bg63at1iwomrwf6/TESTIntro.rar?dl=0

**Comment by avluis** [comment]
Well, I meant the code itself (copy all and paste here) but I can go ahead and take a look at that upload -- brb

**Comment by IcyTower1337** [comment]
I'm sorry for only replying now, I had to leave home for school so I was only able to get back to you now. 

I'm really thankful for the help you've given me, if you dont mind me asking, do I import that library only on the intro activity or do i do it in the build.gradle file?

**Comment by avluis** [comment]
I'm not sure I understand the question.
@Andrew-Quebe Got a minute?

**Comment by IcyTower1337** [comment]
You're not offending, I am welcome for constructive feedback, I will check those out, probably should've been the first thing I should've done. 

Again thank you so much for the help you've given me, I'm really sorry for wasting your time.

**Comment by IcyTower1337** [comment]
@avluis Absolutly, im sorry i didn't close it, i dont know how to do so, can i even close it myself?

**Comment by avluis** [comment]
Yep, you can, as you are the issue OP -- I got it though.
