### ISSUE TITLE
unable to get skip and done buttons besides progress bar

### ISSUE THREAD

**Issue by harshapulikollu** [apl-devs/AppIntro#423]
I just used the  in built add slide method like
addSlide(AppIntroFragment.newInstance("text", "description", R.mipmap.ic_launcher, getResources().getColor(R.color.alertcolor)));
Im able to swipe the between slides but I'm able to get the done button and skip button options in order to move into my main activity.
pic with issue is provided down 
reply me asap
![issue pic](https://cloud.githubusercontent.com/assets/22256553/23702135/07587dde-0420-11e7-9b81-e1f39c36afe3.png)

**Comment by avluis** [comment]
Not really going to be able to help you if you ignore the template -- so the `reply me asap` part is moot here.

**Comment by harshapulikollu** [comment]
Thanks for replying , Im able to get those missed buttons ....

On 08-Mar-2017 7:53 PM, Luis E Alvarado <notifications@github.com> wrote:

Not really going to be able to help you if you ignore the template -- so the reply me asap part is moot here.

**Comment by avluis** [comment]
@harshapulikollu So is this issue resolved?

**Comment by harshapulikollu** [comment]
Yes issue was resolved

On 10-Mar-2017 6:33 AM, Luis E Alvarado <notifications@github.com> wrote:

@harshapulikollu<https://github.com/harshapulikollu> So is this issue resolved?
