### ISSUE TITLE
Making app intro shows once

### ISSUE THREAD

**Issue by herbeytech** [apl-devs/AppIntro#424]
**AppIntro Version**:

**Device/Android Version**:

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by herbeytech** [comment]
How do I make app intro shows just once

**Comment by avluis** [comment]
Please do a bit more research on this - I don't want to be the one telling devs to research:
https://github.com/apl-devs/AppIntro/wiki/How-to-Use#show-the-intro-once
