### ISSUE TITLE
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by razzbee** [apl-devs/AppIntro#427]
Suddenly I am getting this error in my activity file:

```java
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
```

**Comment by avluis** [comment]
It means exactly that -- use a `Theme.AppCompat` theme/style or descendant (based from it).

Please make use of the template whenever creating any issues.
