### ISSUE TITLE
onPageSelected() is called twice after calling pager.setCurrentItem

### ISSUE THREAD

**Issue by AngelJedi** [apl-devs/AppIntro#429]
**AppIntro Version**: 4.0.1

**Device/Android Version**: I've seen it happen on every device I've tried but my main dev device is a Pixel XL 7.1.1, 

**Issue details / Repro steps / Use case background**: 
When calling pager.setCurrentItem(...) I receive two listener callbacks on my OnPageChangeListener.onPageSelected(). I expected to only see one callback occur.

**Your Code**: 
My call to set the current item:
```java
@Override
protected void onPostCreate(@Nullable Bundle savedInstanceState) {
    super.onPostCreate(savedInstanceState);
    if (savedInstanceState == null) {
        pager.setCurrentItem(tipIds.indexOf(showTipId));
    }
}
```

The page listener:

```java
pager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                // do nothing
            }

            @Override
            public void onPageSelected(int position) {
                logAnalytics(position);
            }

            @Override
            public void onPageScrollStateChanged(int state) {
                // do nothing
            }
        });
```

**Stack trace / LogCat**:
No error message

**Comment by AngelJedi** [comment]
It looks like it sets the first page selected before moving to the requested page.

**Comment by AngelJedi** [comment]
It looks like it is setting the first page to be selected before moving to the requested page, which seems like it would be working as designed. Closing this now that I see what is going on.

**Comment by Bharat-sdk** [comment]
> It looks like it is setting the first page to be selected before moving to the requested page, which seems like it would be working as designed. Closing this now that I see what is going on.

did you find the solution what did you do to fix it i also called the function on SCROLL_STATE_IDLE still no proper result
