### ISSUE TITLE
my Pro throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by hegaojian** [apl-devs/AppIntro#430]
I integrated your project before,that is nice,Today, however, your project is integrated, and the result is an error，My English is not skilled, please forgive me ,have a nice day

**Comment by avluis** [comment]
**AppIntro Version**:


**Device/Android Version**:


**Issue details / Repro steps / Use case background**: 


**Your Code**: 


**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by q4401140** [comment]
AppIntro Version: 4.1.0
Device/Android Version: 6.0.1

this is my code:
 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addSlide(SideFragment.newInstance(R.layout.intro2_2_disable));
        addSlide(SideFragment.newInstance(R.layout.intro_2_disable));
        addSlide(SideFragment.newInstance(R.layout.intro3_2_disable));
        setProgressButtonEnabled(false);
    }

I just used compile project a old Version , build apk  is Ok ,no problem, I saw your reply to me,
,i wangt look LogCat,so I delete compile project ,user compile 'com.github.paolorotolo:appintro:4.1.0' ,Surprisingly, my project will, not appear ArrayIndexOutOfBoundsException,I don't know why.have a nice day,and Thank you for your reply!

**Comment by paolorotolo** [comment]
Alright, I'm closing this. Fell free to open another issue if it happens again.

**Comment by Kirkan** [comment]
Same problem on releases after 3.3.0.
```
Intent intro = new Intent(this, Intro.class);
startActivity(intro);
....
public class Intro extends AppIntro {
    private SharedPreferences app_preferences;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        app_preferences = PreferenceManager.getDefaultSharedPreferences(this);
        if (false) {
            addSlide(IntroFragment.newInstance(R.layout.intro1));
        }
        if (false) {
            addSlide(Intro2Fragment.newInstance(R.layout.intro2));
        }
        showSkipButton(false);
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        // Do something when users tap on Skip button.
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        super.onDonePressed(currentFragment);
        this.finish();
    }
}
```
This code throw:
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at java.util.Vector.arrayIndexOutOfBoundsException(Vector.java:907)
	at java.util.Vector.elementAt(Vector.java:328)
	at java.util.Vector.get(Vector.java:442)
	at com.github.paolorotolo.appintro.PagerAdapter.getItem(PagerAdapter.java:32)
	at com.github.paolorotolo.appintro.AppIntroBase$4.run(AppIntroBase.java:192)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
I think you need add not null check in PagerAdapter.getItem(PagerAdapter.java:32)
Thanks!
