### ISSUE TITLE
Unable to remove actionbar in intro/splash activity

### ISSUE THREAD

**Issue by lohriialo** [apl-devs/AppIntro#436]
I'm trying to remove the action bar in my intro/splash activity but somehow I'm unable to get the action bar. actionBar.hide(); causes a null pointer

If your activity extends AppCompactActivity, you can get the action bar fine. When my activity extends AppIntro, how can I remove the action bar?

```
import android.support.v4.app.Fragment;
import android.support.v4.content.ContextCompat;
import android.os.Bundle;
import com.github.paolorotolo.appintro.AppIntro;
import com.github.paolorotolo.appintro.AppIntroFragment;

public class IntroActivity extends AppIntro {

   ActionBar actionBar;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
      
      // this causes the crash
        actionBar = getSupportActionBar(); //also tried getActionBar();
        actionBar.hide();

        addSlide(AppIntroFragment.newInstance("Title 1", "Description of the 1 Slide", R.drawable.intro,
                ContextCompat.getColor(getApplicationContext(), R.color.color_slide1)));

        addSlide(AppIntroFragment.newInstance("Title 2", "Description of the 2 Slide", R.drawable.intro,
                ContextCompat.getColor(getApplicationContext(), R.color.color_slide2)));

        addSlide(AppIntroFragment.newInstance("Title 3", "Description of the 3 Slide", R.drawable.intro,
                ContextCompat.getColor(getApplicationContext(), R.color.color_slide3)));
    }
...
}
```

**Comment by lohriialo** [comment]
Programatically I couldn't remove so I used a custom theme for this particular activity

Define a new theme in styles.xml
```
<style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
</style>
```
In the manifest where you declare your activity, use the theme for that activity like so

```
<activity android:name=".Intro.IntroActivity"
            android:theme="@style/AppTheme.NoActionBar">
</activity>
```

I still would like to remove it programatically, if anyone has some tips, please help

**Comment by amolitos** [comment]
Try this:

```
<style name="themeNoToolbar" parent="Theme.AppCompat.Light.NoActionBar">
      <item name="colorPrimaryDark">@android:color/black</item>
</style>
```

**Comment by avluis** [comment]
AppIntro itself has no reference to the ActionBar, which is why your code is crashing when attempting to get an instance of it (the `instance.hide()` is null, which results in the crash).

Best solutions is to either override `AppIntroBase` or take care of it via Theme/Style (which is usually the preferred method when dealing with libraries).

I'm going to close this, but please reopen this issue if you need further assistance with what I mentioned above.
