### ISSUE TITLE
No skip and Done Button

### ISSUE THREAD

**Issue by punithg** [apl-devs/AppIntro#439]
**AppIntro Version**:Latest

**Device/Android Version**:moto g(first gen),Redmi note 4

**Issue details / Repro steps / Use case background**: its not showing the done button after last slide and also the skip button after enabling

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by avluis** [comment]
It would be very lovely to see some code please...

**Comment by avluis** [comment]
Closing -- I don't see code.
