### ISSUE TITLE
Android Studio Templates

### ISSUE THREAD

**Issue by Ffloriel** [apl-devs/AppIntro#440]
Hey,

I think AppIntro is a great library and I created an android studio template for it in Kotlin.
I put it in this [repo](https://github.com/FullHuman/Kotlin-Android-Studio-Templates/tree/master/AppIntro). I wanted to know if you would be interested in having it here instead.
The template is in Kotlin at the moment. I might be able to do one in Java too. Let me know.

**Comment by avluis** [comment]
I like this approach as it makes it much easier for beginners to implement the library directly into their project.
I personally don't mind if the template is in Kotlin -- though it may be a good idea to keep it in Java since that is what AppIntro uses and what users are expecting.
Do you mind creating a PR once this is ready?

**Comment by Ffloriel** [comment]
I will work on this. I will create a PR once this is ready.

**Comment by paolorotolo** [comment]
This is an interesting approach indeed. @Ffloriel let us know how it's going :)

**Comment by Ffloriel** [comment]
_little update:_
The template seems to work fine.  PR soon.

With the official support of Kotlin in Android Studio 3.0, templates have an additional field to choose the programming language.  
To have a consistent behaviour in Android Studio 2 (current version), I added the same field.

I plan to create 2 templates, one for Android Studio 2 and the other one for v3.
When Android Studio releases 3.0, we can remove Android Studio 2 template.

**Comment by paolorotolo** [comment]
Sounds good!

**Comment by paolorotolo** [comment]
Template available here: https://github.com/apl-devs/AppIntro/tree/master/template
I'm closing this.
