### ISSUE TITLE
Is there any way to go next slide using code?

### ISSUE THREAD

**Issue by jeffersonlicet** [apl-devs/AppIntro#441]
Hi, i want to know if  is there any way to go next slide using code?

Thank you.

**Comment by avluis** [comment]
I believe it is `pager.setCurrentItem(slide_number);`

@jeffersonlicet Make sure to close your issue if the above resolves it <3

**Comment by jeffersonlicet** [comment]
It works!. I think this is not in the documentation as well as doneButton.callOnClick();

**Comment by camhart** [comment]
thanks for this!
