### ISSUE TITLE
ANR on Android 4.x-5.x onCreate

### ISSUE THREAD

**Issue by nicolabeghin** [apl-devs/AppIntro#446]
**AppIntro Version**: 4.2.0
```gradle
compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId = "com.myapp"
        minSdkVersion 11
        targetSdkVersion 25
        versionCode 100
        versionName "3.1.8"
    }

buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }
dependencies {
    compile project(':aFileChooser')
    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:support-v4:25.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'de.mindpipe.android:android-logging-log4j:1.0.3'
    compile 'com.github.apl-devs:appintro:v4.2.0'
    compile 'log4j:log4j:1.2.17'
}
```

**Device/Android Version**: 5.x

**Issue details / Repro steps / Use case background**: App is reported crashing on Android 4.x-5.x, really have no clue about that. Tried downgrading Google libs from 25.3.x to 25.01.0 as shown in some SO threads but issue was not solved. I suppose it's related to Proguard optimization of Appintro lib.

**Your Code**: 
```java
import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;

import com.github.paolorotolo.appintro.AppIntro;

public class IntroActivity extends AppIntro {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        addSlide(SampleSlide.newInstance(R.layout.slide1));
        addSlide(SampleSlide.newInstance(R.layout.slide2));
        addSlide(SampleSlide.newInstance(R.layout.slide3));
        addSlide(SampleSlide.newInstance(R.layout.slide4));
        setBarColor(getColor(R.color.colorPrimary));
    }

    @Override
    public void onSkipPressed(Fragment currentFragment) {
        finish();
    }

    @Override
    public void onDonePressed(Fragment currentFragment) {
        finish();
    }

}
```

**Stack trace / LogCat**:
```java
java.lang.NoSuchMethodError: 
  at com.nbeghin.lib.myapp.IntroActivity.onCreate(IntroActivity.java:0)
  at android.app.Activity.performCreate(Activity.java:6092)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
  at android.app.ActivityThread.access$800(ActivityThread.java:178)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5631)
  at java.lang.reflect.Method.invoke(Method.java:0)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```
**Proguard**
```proguard
-dontwarn org.apache.log4j.**
-keepnames public class com.ianhanniballake.localstorage.LocalStorageProvider
-keepclassmembers public class com.ianhanniballake.localstorage.LocalStorageProvider {
    public static final String AUTHORITY;
}
```

![image 3](https://user-images.githubusercontent.com/2743637/26968520-94d4250c-4d02-11e7-93e0-7d070b533549.png)

**Comment by paolorotolo** [comment]
Are you able to reproduce the issue on your device? If yes, try to build an apk **without** ProGuard, and tell us if it's actually causing the issue.

**Comment by nicolabeghin** [comment]
I'll try to run through Android 5.x emulator and reproduce the issue. I hoped this was something already known, given it's a pretty vanilla implementation of the library. Do you have any specific recommentations related to Proguard when minimizing an app that includes your library?

**Comment by nicolabeghin** [comment]
I confirm, AppIntro makes the app crash on 4.4. I just reproduced the issue on the emulator. Could you provide the APK for a proguard-ed version of your example app?

**Comment by avluis** [comment]
@nicolabeghin Let's worry about _one issue_ at a time -- what you are seeing with the example app has already been reported.
Also, are those all of your ProGuard rules? Do you have anything for your own classes defined?

If you can clarify what you said here:
> I confirm, AppIntro makes the app crash on 4.4. I just reproduced the issue on the emulator. The example APK example-release-v1.apk for AppIntro crashes too:

Is this with ProGuard **enabled** or **disabled**?

**Comment by nicolabeghin** [comment]
@avluis, thanks for your reply.

1. yes those are all of my ProGuard rules
2. I just used the published APK on the repository, don't know if that has Proguard enabled or not https://github.com/apl-devs/AppIntro/blob/master/example/example-release-v1.apk
3. I compiled the example app straight from repository (master) and run on Android 4.4 + Android 6.0 and got no button shown - this could have helped me debug the whole thing, but being unable to get the example app working (no buttons) it didn't help

**Comment by avluis** [comment]
@nicolabeghin ProGuard is defined but not enabled for the example project -- since you got it to run and all that.
From your logs;
I can tell that ProGuard is cleaning up way too much out of your own classes -- you may need a few additional rules.
I would give you a few more pointers but I'm currently waiting on Android Studio to finish patching in all these updates... 🤦

**Comment by avluis** [comment]
@nicolabeghin Here is an [example of what it can take](https://github.com/AVnetWS/Hentoid/blob/master/app/proguard-project-app.pro) to configure ProGuard for a project. (note that this is a personal project and not related to AppIntro)
I hope this helps! Let us know if you need additional pointers~

**Comment by nicolabeghin** [comment]
hi @avluis thanks for the pointers, I'll surely take a look (I used proguard rules repositories for other projects of mine, extremely useful). But I don't think this will fix the issue as you already saw my app proguard rules and they don't add anything specific, so if AppIntro proguard rules _do_ work they should work in the app too.

```proguard
-dontwarn org.apache.log4j.**
-keepnames public class com.ianhanniballake.localstorage.LocalStorageProvider
-keepclassmembers public class com.ianhanniballake.localstorage.LocalStorageProvider {
    public static final String AUTHORITY;
}
```

**Comment by avluis** [comment]
@nicolabeghin You can always add `-keep class com.github.paolorotolo.** {*;}` to your ProGuard file to do a quick test of the library against your app -- this should keep ProGuard from doing anything to AppIntro (which would then let us know if we are missing something) -- _note that the example app is running on a different package namespace, so keep that in mind if you want to try running ProGuard against that._

If you get the same behavior as before (application crashing), then you can at least eliminate the library from your troubleshooting list~

**Comment by nicolabeghin** [comment]
I'll surely check that tonight, I have the dump.txt generated by ProGuard and this should shed some light on the whole thing (if AppIntro classes are obfuscated it means ProGuard rules are not taken into considerations, as I see from `consumer-proguard-rules.pro` https://github.com/apl-devs/AppIntro/blob/master/library/consumer-proguard-rules.pro)
`-keep class com.github.paolorotolo.** {*;}`

**Comment by nicolabeghin** [comment]
I think I narrowed it down. App crashes without ProGuard enabled too, but I was able to get more info from the logcat:

```java
java.lang.NoSuchMethodError: com.nbeghin.myapp.IntroActivity.getColor
    at com.nbeghin.lib.myapp.IntroActivity.onCreate(IntroActivity.java:22)
    at android.app.Activity.performCreate(Activity.java:5231)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
    at android.app.ActivityThread.access$800(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5001)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
    at dalvik.system.NativeStart.main(Native Method)
```

It stopped crashing changing `setBarColor(getColor(R.color.colorPrimary))` to 
 `setBarColor(ContextCompat.getColor(this, R.color.colorPrimary))`

I have *no* clue about this. I'm trying to understand why, of course `getColor` is defined in `android.content.Context`

```java
@ColorInt
public final int getColor(@ColorRes int id) {
    return getResources().getColor(id, getTheme());
}
```

**Comment by avluis** [comment]
Ah~ I've seen this before on prior projects.
You definitely want to make use of `ContextCompat` whenever possible when using the newer tools.
