### ISSUE TITLE
Swipe Permission

### ISSUE THREAD

**Issue by MHKalantarian** [apl-devs/AppIntro#451]
Hi, when I set swiping enabled it doesn't ask on permission when swiping the permission fragment, the next button works fine for asking but it doesn't ask when swiping that fragment.

**Comment by avluis** [comment]
https://github.com/apl-devs/AppIntro#runtime-permissions-android-60

**Comment by idish** [comment]
Why is this issue so obvious? I saw alot of people opened an issue regarding this, and there must be many more users who haven't bothered to do so, as your readme says. 
I think it's a shame that this is the current situation. Is there any hard logical reason behind this behavior?
