### ISSUE TITLE
How to Call a method in Fragements When Skip button is pressed

### ISSUE THREAD

**Issue by vigneshwarcet** [apl-devs/AppIntro#461]
**AppIntro Version**:4.0.0

**Device/Android Version**: Emulator

**Issue details / Repro steps / Use case background**: 

**Your Code**: 

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

How to call a method inside a fragment when Skip button clicked

**Comment by avluis** [comment]
You need to research how to interact with fragments (you interact with the activity hosting them).
As for the skip button:

```java
    @Override
    public void onSkipPressed(Fragment currentFragment) {
        super.onSkipPressed(currentFragment);
        finish(); // Your method would replace this
    }
```
