### ISSUE TITLE
Android studio compile Error.

### ISSUE THREAD

**Issue by rb0071** [apl-devs/AppIntro#463]
Error:(40, 13) Failed to resolve: com.github.apl-devs:appintro:v4.2.0

Error:Failed to resolve: annotationProcessor

**Comment by novas1r1** [comment]
Same problem here

**Comment by novas1r1** [comment]
Did you add this one:

// Add it in your root build.gradle at the end of repositories:

	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

? Worked for me :)

**Comment by rb0071** [comment]
@novas1r1 Thank you. Worked! 👍  👍

**Comment by avluis** [comment]
@novas1r1 If your issue has been resolved, go ahead and close it.

**Comment by shareefhiasat** [comment]
its back again for ERROR: Failed to resolve: com.github.paolorotolo:appintro:v5.1.0 :(

**Comment by cortinico** [comment]
@shareefhiasat Do you have Jitpack in your repositories?

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
