### ISSUE TITLE
i got failed to resolve

### ISSUE THREAD

**Issue by iotwebplanet** [apl-devs/AppIntro#467]
Error:(34, 13) Failed to resolve: com.github.apl-devs:appintro:v4.2.1
<a href="openFile:/----/AndroidStudioProjects/AppIntro2/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

i m using 

 maven { url 'https://jitpack.io' }
compile 'com.github.apl-devs:appintro:v4.2.1'

**Comment by vivekaris** [comment]
Error:(34, 12) Failed to resolve: com.github.apl-devs:appintro:v4.2.1
Show in File
Show in Project Structure dialog

i m using

maven { url 'https://jitpack.io' }
compile 'com.github.apl-devs:appintro:v4.2.1'

**Comment by vivekaris** [comment]
repositories {
       ----------
        maven { url 'https://jitpack.io' }
    }
}

this is soved

**Comment by avluis** [comment]
@iotwebplanet Where are you adding the maven declaration for JitPack?
@vivekaris Are you @iotwebplanet or has your particular issue being solved?

**Comment by jbhingradiya** [comment]
@vivekaris i am still getting this error adding repositories {
----------
maven { url 'https://jitpack.io' }
}
}

**Comment by willblaschko** [comment]
This should solve your problem:
https://stackoverflow.com/a/41529064/2353588

**Comment by shareefhiasat** [comment]
In short Use latest android studio with latest gradle
