### ISSUE TITLE
How to change slides programmatically

### ISSUE THREAD

**Issue by abicelis** [apl-devs/AppIntro#475]
I'd like to change a slide programatically, is there a way to do that I am not seeing?

Maybe through AppIntroBase:     
`private void changeSlide(boolean isLastSlide);
`

Thanks for the awesome lib!

**Comment by paolorotolo** [comment]
Sure thing, just call:
```java
getPager().setCurrentItem(id);
```

where ```id``` is an Integer with the slide id you want to go on.

Let us know if it solved the issue.

**Comment by avluis** [comment]
@abicelis Does the above suggestion address your issue?

**Comment by agueroveraalvaro** [comment]
Yes it works but add a new fragment in its position, then my question is: 
can i delete a fragment added??
(to not duplicate)

**Comment by abicelis** [comment]
@paolorotolo @avluis Yes it works great!
Thank you!

**Comment by paolorotolo** [comment]
Good, closing this.
