### ISSUE TITLE
Transparent Status Bar Bug

### ISSUE THREAD

**Issue by ofirmiron** [apl-devs/AppIntro#476]
Hello,
I just upgraded to version 4.2.2 from version 4.2.0 and possibly found a new bug. In the previous version, I was able to make the statusbar transparent using the following in the v21\styles.xml:
`<item name="android:statusBarColor">@color/statusBarSemiTransparent</item>
<item name="android:windowIsTranslucent">true</item>
<item name="android:windowBackground">@android:color/transparent</item>`

And the following line of code in the onCreate of the activity:
`if (android.os.Build.VERSION.SDK_INT >= 19) {
            getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
}`

However, on the latest version the statusbar defaults to black.

Version 4.2.0:
![4 2 0](https://user-images.githubusercontent.com/17969689/29355314-64eaeada-8225-11e7-9ed2-55dc4538838b.png)

Version 4.2.2:
![4 2 2](https://user-images.githubusercontent.com/17969689/29355317-66b375bc-8225-11e7-8ffe-49034abbac3a.png)

**Comment by paolorotolo** [comment]
Hey!
Just declare a theme in your ```styles.xml``` that has a *TranslucentStatus* parent.
For example:

```xml
    <style name="AppIntroTheme" parent="MaterialTheme.TranslucentStatus">
        <item name="colorPrimary">#1976D2</item>
        <item name="colorPrimaryDark">#1565C0</item>
        <item name="colorAccent">#E91E63</item>
    </style>
```

Then in your ```AndroidManifest.xml``` set the theme to AppIntro's activity:

```xml
        <activity
            android:name=".AppIntroActivity"
            android:theme="@style/AppIntroTheme"/>
```

**Comment by paolorotolo** [comment]
Anyway, I've found our Example app doesn't have translucent status bar. I've updated it, maybe it help out other devs.

**Comment by santhoshvai** [comment]
I have the same issue, setting a translucent theme also doesnt make it work. I see the black.

**Comment by localhostEU** [comment]
@paolorotolo What if there's a custom fragment with ImageView at the top? They way to place ImageView behind status bar is to declare a windowTranslucentStatus true. And that worked for previous versions.
