### ISSUE TITLE
Integrate a loading spinner?

### ISSUE THREAD

**Issue by JamesHealdUK** [apl-devs/AppIntro#487]
Loving this library! Only thing is, when it comes to setting up a user for the first time (and uploading said data to a server), its in dire need of `ProgressBar` functionality.

For example, when I upload my avatar and set my username and press the "Done" button, itd be good to have a spinner take its place to signify that its uploading.

**Comment by avluis** [comment]
Unfortunately this would be outside the scope of AppIntro.

What I can say though, is that I make use of the [Material Dialogs](https://github.com/afollestad/material-dialogs) library, which includes what you need (`ProgressBar`'s and the like).

From your description, you'll need to create an activity that will receive `onActivityResult` (from `startActivityForResult`) to display the upload progress, transform into a ✔️ when done (as well as error handling) and dismiss itself.
