### ISSUE TITLE
askForPermissions method cause sliding not working

### ISSUE THREAD

**Issue by winsontan520** [apl-devs/AppIntro#490]
I run your example code found that the permission demo cannot slide. Then I comment the method askForPermissions then it can slide again.
Suspect the askForPermissions cause sliding not working

**Comment by paolorotolo** [comment]
It's an intended behaviour. From README:
```
NOTE 2: Requesting permissions automatically disables sliding, and users will have to result to pressing the buttons. Please do not open any issues regarding this, as they will be immmediately closed. Thanks!
```
