### ISSUE TITLE
 Add to "Apps using Lib" section

### ISSUE THREAD

**Issue by djuelg** [apl-devs/AppIntro#496]
Hey there,

today I will release my note app Neuronizer to production on Google play.
As I decided to use your library it would be nice to be listed in the app section.
Here are the links:
https://github.com/djuelg/Neuronizer
https://play.google.com/store/apps/details?id=de.djuelg.neuronizer

Greets,
djuelg

**Comment by avluis** [comment]
_Moved_: https://github.com/apl-devs/AppIntro/issues/325
@djuelg
