### ISSUE TITLE
AppIntro runs everytime I open the app

### ISSUE THREAD

**Issue by Kvaibhav01** [apl-devs/AppIntro#497]
**AppIntro Version**: 4.2.2

**Device/Android Version**: Works great on every device. I use [Yu Yureka](https://www.gsmarena.com/yu_yureka-6987.php) as physical and Nexus 5X as emulated device for testing.

**Issue details**: I've implemented how to run the AppIntro slides only for the first time from the [AppIntro Wiki](https://github.com/apl-devs/AppIntro/wiki/How-to-Use#show-the-intro-once). I also added the [Manifest declaration ](https://github.com/apl-devs/AppIntro/wiki/How-to-Use#add-a-manifest-declaration) but still, **everytime I open the app from my physical or emulated device, it runs each time**! How do I resolve this?

**Your Code**: My MainActivity.java (actually it's EarthquakeActivity.java)-

```
//Start the intro slide with an intent
        Intent intent = new Intent(this, IntroActivity.class);
        startActivity(intent);

        /* Start the intro only once */
        //  Declare a new thread to do a preference check
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                //  Initialize SharedPreferences
                SharedPreferences getPrefs = PreferenceManager.getDefaultSharedPreferences(getBaseContext());

                //  Create a new boolean and preference and set it to true
                boolean isFirstStart = getPrefs.getBoolean("firstStart", true);

                //  If the activity has never started before...
                if (isFirstStart) {

                    //  Launch app intro
                    final Intent i = new Intent(EarthquakeActivity.this, IntroActivity.class);

                    runOnUiThread(new Runnable() {
                        @Override public void run() {
                            startActivity(i);
                        }
                    });

                    //  Make a new preferences editor
                    SharedPreferences.Editor e = getPrefs.edit();

                    //  Edit preference to make it false because we don't want this to run again
                    e.putBoolean("firstStart", false);

                    //  Apply changes
                    e.apply();
                }
            }
        });

        // Start the thread
        t.start();
```
My Manifest file-

```
<activity android:name="com.example.android.quakereport.IntroActivity"
            android:label="@string/app_intro" />
```
I've added a new String resource in Strings.xml-

`<string name="app_intro">Intro</string>`

**Comment by avluis** [comment]
I'm sorry, but this is not an AppIntro issue -- yes, looks like the wiki needs to be expanded further for those that are making use of preferences for the first time, but we can't take the time to guide everyone who uses the library on how to open an activity only when needed.

Stackoverflow has plenty of questions regarding this subject and it is the resource I recommend all developer to query (not post).
