### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by alexbertis** [apl-devs/AppIntro#542]
When will we get support for AndroidX? (I mean, the only need is to refactor this)

AppIntro v4.2.3

**Comment by cortinico** [comment]
PR is here #544

**Comment by paolorotolo** [comment]
After @cortinico's pull I guess it will happen very soon :)

**Comment by alexbertis** [comment]
Meanwhile, a possible workaround I have found is to set the `android.enableJetifier=true` flag in the `gradle.properties` file, and in the module's `build.gradle` implement the library as follows: 
`implementation ('com.github.apl-devs:appintro:v4.2.3') {
        exclude group: "com.android.support"
    }`

I am aware of the possible incompatibility issues that AndroidX could generate in apps which don't target the last SDK.

**Comment by prasannajeet** [comment]
I am not able to get your solution to work for me @alexbertis . I am getting errors on android support annotations, v4.Fragment and AppCompatActivity. I tried to resolve it by adding implementation 'com.android.support:appcompat-v7:27.1.1' but I ended up with "Program type already present: android.support.v4.os.ResultReceiver$1" again. I guess I will be waiting for your PR to be merged before I can proceed ahead with the integration

**Comment by alexbertis** [comment]
I haven't made a pull request, I expect others to find a better solution to this problem. If you use AndroidX, don't include the older versions of Android Support Library, this will cause incompatibilities. I only get errors from Lint, but at runtime (which is the key part) everything works fine.

**Comment by prasannajeet** [comment]
Agreed. Waiting for @paolorotolo to approve the PR by @cortinico!

**Comment by paolorotolo** [comment]
Here you go!
Thanks again for the contribution @cortinico,

**Comment by cortinico** [comment]
You're more than welcome @paolorotolo 👍
