### ISSUE TITLE
changed dependency URL? Not Working

### ISSUE THREAD

**Issue by pratikbutani** [apl-devs/AppIntro#555]
I have used before:

implementation 'com.github.paolorotolo:appintro:4.2.3'

Currently Getting Errors so I saw and Its displaying following URL.
implementation 'com.github.apl-devs:appintro:v4.2.3'

Is it really?

**Comment by cortinico** [comment]
Looks like a duplcate of #556 
@paolorotolo can you close?

**Comment by paolorotolo** [comment]
Hey @pratikbutani,
can you please verify if you have added the right repo in your top level build.gradle?
```
maven { url 'https://jitpack.io' }
```
