### ISSUE TITLE
Kotlin in the Repo?

### ISSUE THREAD

**Issue by cortinico** [apl-devs/AppIntro#560]
_This is more a question rather than an issue._

Are we fine with adding Kotlin to the repo?
I'd love to convert some classes to Kotlin.

Also, I think we will benefit from Kotlin DSL if we use them in the SliderPage builder.
Happy to discuss/brainstorm :)

I'm asking before doing a PR that might eventually be rejected.

**Comment by cortinico** [comment]
> Actually maybe it's better to set up a Gitter group to allow discussions
from developers about Appintro.

Definitely! :)
Don't you mind creating the room?

**Comment by paolorotolo** [comment]
Here you go!
https://gitter.im/AppIntro/Lobby

I've also updated README.
