### ISSUE TITLE
I wonder if the method setAnimationColors(ArrayList<Integer> colors) is useful.

### ISSUE THREAD

**Issue by qianshengta** [apl-devs/AppIntro#580]
**AppIntro Version**:
AppIntro Version：4.2.3

**Device/Android Version**:
null

**Issue details / Repro steps / Use case background**: 
I looked at the source code，ArrayList set through "setAnimationColors(ArrayList<Integer> colors)" are not used by any objects.I wonder if the method setAnimationColors(ArrayList<Integer> colors) is useful.

**Your Code**: 
null

**Stack trace / LogCat**:
null

**Comment by cortinico** [comment]
Yeah you're right. That method can be removed.
Here the PR @paolorotolo #582

**Comment by paolorotolo** [comment]
#582 is merged now.
Thanks for the contribution.
